# fly.toml app configuration file generated for ariadne-api on 2026-03-24T09:50:01-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ariadne-api'
primary_region = 'iad'

[build]
  dockerfile = './Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '15s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
